### PR TITLE
Feature/refactor css to tailwind

### PR DESCRIPTION
**Pull request by nicholemcgrew**
Converted CSS to Tailwind and refactored code to fix errors where needed.

### CODE REVIEW

**Comment by ghost** [comment]
I don't think that the styling on the registration form is doing what you intend for it to do:

image

I also notice a lot of elements with the same set of classNames. According to the [tailwind docs](https://tailwindcss.com/docs/reusing-styles) it is recommended to make a component when you want to reuse styles. For instance, if you use the same styling on all of the input elements, you create one RegistrationFormInput component and apply the classNames to that and use that component in the place of all of the input elements.

**Comment by nicholemcgrew** [comment]
Thank you for pointing this out, I'm looking at it now.

*Nichole McGrew*
C: (405) 204-0296 | ***@***.***

**Comment by nicholemcgrew** [comment]
Code has been updated and is ready for review. :)

*Nichole McGrew*
C: (405) 204-0296 | ***@***.***

**Review by ghost — APPROVED** [review]
This looks good!

**Comment by tysonlind** [comment]
I noticed that when I pull up the modal, it has a scroll overflow on it. This doesn't look great on mobile or desktop. Is this a behavior that was happening before the refactor? We may also want to look into why the UI flashes dark before applying the styling if you then close the modal. I'm going to approve this, though, because the tailwind changes look accurate. These are just comments to make a note of this stuff.

**Review by tysonlind — APPROVED** [review]

**Pull request merged**
